# Generated by Django 4.2.8 on 2023-12-30 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Account",
        ),
    ]
