# Generated by Django 4.2.8 on 2023-12-31 01:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Account",
        ),
    ]
